import { useQuery } from "react-query";

function useMatchDetailQuery(matchId) {
  return useQuery({
    queryKey: ["matchdetail", matchId],
    queryFn: async () => {
      const res = await fetch(`/api/getMatchDetail/${matchId}`);
      const json = await res.json();

      return json;
    },
    placeholderData: {
      date: "2023-08-06 23:00",
      gameTypeId: "rating",
      map: {
        mapId: "101",
        name: "리버포드",
      },
      teams: [
        {
          result: "lose",
          players: [
            "b98f46acc90cb146e74281eb4013871d",
            "16202b49d2c2a242eb0fca2b28475a8b",
            "507a8e01d95536925e76a3d39e3c05b6",
            "8abac87df02214b4130c4351b59375d6",
            "1163dfae07e7cfbef54534090b3d5fdf",
          ],
        },
        {
          result: "win",
          players: [
            "b91e779ee4bd225a46f08728f589276c",
            "6b81d82d42b38074dd4bb1fe01776e25",
            "3346ad34f984fdda1b7e37c725acddc8",
            "0ae4f1beb3575fa751c583d4b8f6e05d",
            "9fbaacf5e93cf721fb31c01f305847db",
          ],
        },
      ],
      players: [
        {
          playerId: "b98f46acc90cb146e74281eb4013871d",
          nickname: "토레기",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 0,
            partyId: "b762303013093c43599c55f64fdcff53",
            playTypeName: "정상",
            characterId: "caa0168d0c68ec4dfe64d025df2673f0",
            characterName: "아이작",
            level: 26,
            killCount: 0,
            deathCount: 7,
            assistCount: 4,
            attackPoint: 3945,
            damagePoint: 48175,
            battlePoint: 144,
            sightPoint: 241,
            towerAttackPoint: 133,
            backAttackCount: 10,
            comboCount: 6,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 5,
            demolisherKillCount: 2,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 8130,
            spendCoin: 7750,
            spendConsumablesCoin: 2400,
            playTime: 888,
            responseTime: 144,
            minLifeTime: 10,
            maxLifeTime: 306,
          },
          position: {
            name: "탱커",
            explain: "체력 +7%, 회피 +5%",
            attribute: [
              {
                level: 1,
                id: "6d8fb905d69edf1c9f73495c3ee44d28",
                name: "선봉장",
              },
              {
                level: 2,
                id: "1d49c4504c55a43f670d4d69575760d4",
                name: "재생의 숨결",
              },
              {
                level: 3,
                id: "678bca255e575ae96aceefacaa7aee4e",
                name: "최후의 저항",
              },
            ],
          },
          items: [
            {
              itemId: "58d3a2410391933ab9e40de2cc2b7f61",
              itemName: "E 리트릿 프리벤트",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "dfeb3975bb25b631025dd594c769d26d",
              itemName: "언노운 페이스",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "b3a4671081d601d65dc2114d4fa0215d",
              itemName: "S 빅 블랙 머신",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "d7d3db29e44b9f9cb37fa776b2089cd0",
              itemName: "S 인휴먼 퍼슈어",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "3a3e4d188d5806203c37ce89b0b92f8e",
              itemName: "E 킬링 머신",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "8ef23a5ac4da682b801b36db14bfc2d0",
              itemName: "S 데드 컨트랩션",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "f20e6f5322e1070c3f55f11f236c24d6",
              itemName: "저지먼트 레그람",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "e194c0e00fbd1b28fa762b5035de6555",
              itemName: "레이지 레그람",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "6680ccd0ed62d2ab0e1cfdbcfac8a79c",
              itemName: "블랙 스파클링 ",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "5b9a8108b0b92457abc225c565fde466",
              itemName: "리세스 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "7c373d1b093c600863bbee2a46f53e52",
              itemName: "블랙 파이크 ",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "2e68b656a3f4d3e4ac535f5c9fb4890f",
              itemName: "블랙 플래쉬",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "8be7e6254b58ecbf2a13e81931a7435f",
              itemName: "인사이트 엔진T7 ",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "f3d9921bbd7dc3b3c3fb5f9a3203a3c1",
              itemName: "어벤징 이모션",
              slotCode: "107",
              slotName: "목",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "6115a58bebb8be90c4e9e0581d9768b0",
              itemName: "데드맨 레그람",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "6f6ce4129bbd0fe8e1cebc0cf29bfb2e",
              itemName: "데몰리쉬 에너미",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "b91e779ee4bd225a46f08728f589276c",
          nickname: "댕인호",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 2,
            partyId: "d8264261c6d147a0bfe5e68b17579e7b",
            playTypeName: "정상",
            characterId: "7d1e6070ba8b5671a5c2373dfa4ffa1c",
            characterName: "미아",
            level: 57,
            killCount: 10,
            deathCount: 1,
            assistCount: 11,
            attackPoint: 42331,
            damagePoint: 7496,
            battlePoint: 181,
            sightPoint: 241,
            towerAttackPoint: 87847,
            backAttackCount: 51,
            comboCount: 81,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 15,
            demolisherKillCount: 35,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 2,
            getCoin: 17790,
            spendCoin: 17650,
            spendConsumablesCoin: 3200,
            playTime: 888,
            responseTime: 15,
            minLifeTime: 136,
            maxLifeTime: 737,
          },
          position: {
            name: "원거리딜러",
            explain: "치명타 피해량 +12%",
            attribute: [
              {
                level: 1,
                id: "3a161b331b17d723237b2af3f1000022",
                name: "태세전환",
              },
              {
                level: 2,
                id: "43c56f15f90192f7ead0a8eba794fbed",
                name: "전장의 학살자",
              },
              {
                level: 3,
                id: "abd29ed2134647107bdf5bfaa424a494",
                name: "전장의 열기",
              },
            ],
          },
          items: [
            {
              itemId: "a149b275f98539c0b34704c8737c2ef0",
              itemName: "E 이볼브 가이아",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "018b93227096cfd4c447760eca47f860",
              itemName: "E 디바인 그레이스",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "566a91b5f4c2d44493acab198bf21870",
              itemName: "E 옐로우 루트웨이브",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "150bb9f490a667ac0ff93bc9eca2ddd7",
              itemName: "E 프릭클 에린",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "ba649e1490a627bfd18acff34dc85bfd",
              itemName: "E 와일드 크로스",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "f87e29c9dc815a3f8b9b94310b4845c7",
              itemName: "E 이네이쳐 게브",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "abc01de55a55f3516a146023fc5c673e",
              itemName: "도장 바이리프",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "2844fc5e7d9b7dfc469799b609245e03",
              itemName: "가시 바이리프",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "914ef8cf72b10af27bafd687210ae940",
              itemName: "체스터 더블버거",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c4388fe669e6538e6c525cd39ec60e82",
              itemName: "우드 엑셀",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "cb34687057d7bedc8c55cd4445fedf50",
              itemName: "우드 파이크 ",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "a5829b6da66c7bb983e58fc5cc207f30",
              itemName: "솔리드 스위퍼",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "f623c1b7170ddcbe77837d0e33b07e4e",
              itemName: "세계수 맥시머",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "05e096c3f2983da8e8d01814bb8a5a05",
              itemName: "E 레드 크로니클",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "3d32b2e64bc34a61d79c6b9ffc75e513",
              itemName: "뿌리 바이리프",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "ba1d4d23a7448b56b6e8d7049434ef52",
              itemName: "트리콜로 트와인",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "6b81d82d42b38074dd4bb1fe01776e25",
          nickname: "톳데모이이요나",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 0,
            partyId: "b762303013093c43599c55f64fdcff53",
            playTypeName: "정상",
            characterId: "798afd40efb445158c963b6de2588a6e",
            characterName: "토마스",
            level: 39,
            killCount: 2,
            deathCount: 2,
            assistCount: 22,
            attackPoint: 10957,
            damagePoint: 12671,
            battlePoint: 179,
            sightPoint: 262,
            towerAttackPoint: 2400,
            backAttackCount: 31,
            comboCount: 28,
            spellCount: 35,
            healAmount: 0,
            sentinelKillCount: 11,
            demolisherKillCount: 1,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 11590,
            spendCoin: 11450,
            spendConsumablesCoin: 2200,
            playTime: 888,
            responseTime: 36,
            minLifeTime: 127,
            maxLifeTime: 377,
          },
          position: {
            name: "서포터",
            explain: "주변 아군의 스킬 공격력 +3%, 방어력 +4%, 회피 +4%",
            attribute: [
              {
                level: 1,
                id: "d934a4115b67e67b4cbcbc892e172c1b",
                name: "협동 공격",
              },
              {
                level: 2,
                id: "3243d03592dfb43f7acef5203e95bb09",
                name: "신경쇠약",
              },
              {
                level: 3,
                id: "100b40cb5e22f5613492234dcba705c6",
                name: "활성화 지원",
              },
            ],
          },
          items: [
            {
              itemId: "22f4720521fb69b89aede8e72240fec6",
              itemName: "E 아이스 컴포지션",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "b99afb71fd7668e99b00482b86d8382c",
              itemName: "잭 아이실드 ",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "96ea282087c2398b7dfa01cefab36465",
              itemName: "S 윈터 히어로",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "8a6fc195453cd01221b9fb11a1d50f0e",
              itemName: "S 스노우 플라워",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "9455bc8c585595b6708e236a269b355e",
              itemName: "S 미스틱 아이스",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "8e678a6a46c8629f73345f4dda90239f",
              itemName: "E 블리자드 기어 ",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "ca3a99302c679316548a2614298a73f9",
              itemName: "빙산 레그람",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "35fa92417f07531df908c02e5faeeb7d",
              itemName: "프리즌 콜드밴드",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "26b2981ec73f48b10c391d49aabffeaa",
              itemName: "쿨 스파클링 ",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c0432d98a1e2d21bda6e726ef4dafce3",
              itemName: "런업 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "ff06d688624c6edf48ff8386e75c5b64",
              itemName: "프로스트 이펙트 ",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "cd4e84dccbb310805fc701507b448c23",
              itemName: "프로스트 타즈 ",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "a6abfd4505fb46cde75dc5b4414b60b8",
              itemName: "PS 레이더 R4",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "147cea4b1c6a5b1c9f437481a4682af8",
              itemName: "E 프로스트 솔리드",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "6437448e0cfc02a15e6118007fd650da",
              itemName: "냉각 도스프로퍼",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "aa0cbb61f4ecd32a0a2629d23ea9a79e",
              itemName: "설풍 레그람",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "16202b49d2c2a242eb0fca2b28475a8b",
          nickname: "Solidity",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 0,
            partyId: "b762303013093c43599c55f64fdcff53",
            playTypeName: "정상",
            characterId: "29863fca436fc32196f3b07b1b80d6eb",
            characterName: "라이언",
            level: 29,
            killCount: 1,
            deathCount: 7,
            assistCount: 3,
            attackPoint: 8380,
            damagePoint: 39282,
            battlePoint: 166,
            sightPoint: 267,
            towerAttackPoint: 0,
            backAttackCount: 10,
            comboCount: 20,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 7,
            demolisherKillCount: 1,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 8550,
            spendCoin: 8400,
            spendConsumablesCoin: 2100,
            playTime: 888,
            responseTime: 153,
            minLifeTime: 13,
            maxLifeTime: 210,
          },
          position: {
            name: "탱커",
            explain: "체력 +7%, 회피 +5%",
            attribute: [
              {
                level: 1,
                id: "ce65e78d295a624270d418ebafa8d1c0",
                name: "기민한 몸놀림",
              },
              {
                level: 2,
                id: "711f424bc5801dcdee09eee1863f5e0e",
                name: "낙법",
              },
              {
                level: 3,
                id: "6d8fb905d69edf1c9f73495c3ee44d28",
                name: "선봉장",
              },
            ],
          },
          items: [
            {
              itemId: "db3249dd3a15f06d3502557a11bedc29",
              itemName: "S 크리티컬 블로우",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "851f6da24f68b1d3864d3b825d054197",
              itemName: "E 끔찍한 기억",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "7b9d9ef6f5868e1c6da9fe206393a64d",
              itemName: "E 아름다운 지평선",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "1933e1b13ef680b516c11323e29d8947",
              itemName: "RA완벽한 마지막",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "20c2e907a99f4e7516fc013f22710c4a",
              itemName: "E 디펜시브 엔드",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "0f3b512eafbb99322b93d5d49cedcdf3",
              itemName: "S 오후의 죽음",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "a2ba568ab53cfdae6d0625cab9919990",
              itemName: "블리츠 레그람",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "42c88a7e1a64f016826d14d83391cffa",
              itemName: "블로킹 레그람",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "e5cd644b6614097fbb71139b9a5d4314",
              itemName: "스톤 스파클링",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c0432d98a1e2d21bda6e726ef4dafce3",
              itemName: "런업 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "4c8b421f78550776e4dc8bf3f95afa9b",
              itemName: "스톤 파이크",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "ce3256055ab8493ce459ee0298b5d19d",
              itemName: "스톤 타즈",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "cf4fdb7f6499d6ebc62c21746e66bfe7",
              itemName: "T11-스파이더",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "dd97f6d5d430bc1956b6b0e12dd74960",
              itemName: "S 최고의 수비수",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "93f456716b2c4e7dd46d801fb8a78863",
              itemName: "스매시 부토니에",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "75f4d7a6a573dc9b4ec020f48385b72e",
              itemName: "오지 않을 미래",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "3346ad34f984fdda1b7e37c725acddc8",
          nickname: "전인석",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 2,
            partyId: "d8264261c6d147a0bfe5e68b17579e7b",
            playTypeName: "정상",
            characterId: "6d7db858c4f20adcf4fc2eee21c2c03f",
            characterName: "브루스",
            level: 35,
            killCount: 1,
            deathCount: 2,
            assistCount: 12,
            attackPoint: 9255,
            damagePoint: 21645,
            battlePoint: 182,
            sightPoint: 358,
            towerAttackPoint: 4011,
            backAttackCount: 25,
            comboCount: 36,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 13,
            demolisherKillCount: 1,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 10330,
            spendCoin: 9600,
            spendConsumablesCoin: 2600,
            playTime: 888,
            responseTime: 31,
            minLifeTime: 145,
            maxLifeTime: 360,
          },
          position: {
            name: "탱커",
            explain: "체력 +7%, 회피 +5%",
            attribute: [
              {
                level: 1,
                id: "678bca255e575ae96aceefacaa7aee4e",
                name: "최후의 저항",
              },
              {
                level: 2,
                id: "711f424bc5801dcdee09eee1863f5e0e",
                name: "낙법",
              },
              {
                level: 3,
                id: "6d8fb905d69edf1c9f73495c3ee44d28",
                name: "선봉장",
              },
            ],
          },
          items: [
            {
              itemId: "165112e16058a4a31da3cb8d950abc79",
              itemName: "E 거침없는 발톱",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "5fc1855072ff34c706c05595bf25fe18",
              itemName: "파워풀 대쉬",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "1ef1aba18e798bc6100142d4c1d48310",
              itemName: "E 야성의 심장",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "f30e653024e01c3c6530ea999a9aa6c5",
              itemName: "E 승리의 상징",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "b21cddb2d9d21110128ec6c3e1bb27ef",
              itemName: "E 진중한 탐험가",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "2f5cf2ed048c238906dd20c2b011178d",
              itemName: "E 기나긴 여정",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "f40c053e23267f843c2dda2affe3389d",
              itemName: "맹수 레그람",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "3158d1c52af701ad0412c60c561214e6",
              itemName: "베어 코토스",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "ea7165e36f414bf19cfb202c82cdc338",
              itemName: "야수 스파클링 ",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c0432d98a1e2d21bda6e726ef4dafce3",
              itemName: "런업 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "d73dcc74e8b50ec835eff3c50da5f13f",
              itemName: "야수 파이크 ",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "7626d08a5ed48dae6162d594ee9052f6",
              itemName: "야수 플래쉬",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "cf4fdb7f6499d6ebc62c21746e66bfe7",
              itemName: "T11-스파이더",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "c6b7e04e686da81f0938b1690284ea18",
              itemName: "스트롱 비스트",
              slotCode: "107",
              slotName: "목",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "ecfe484224d33be3d17b9c02f9378a96",
              itemName: "하울링 레그람",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "1f0ef54fa06153a5bfda12b5a44f9881",
              itemName: "헌팅 레그람",
              slotCode: "201",
              slotName: "장신구ALL",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "507a8e01d95536925e76a3d39e3c05b6",
          nickname: "ㅡFURYㅡ",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 2,
            partyId: "ce31afb4198335842df5f7c43beb3b6b",
            playTypeName: "정상",
            characterId: "df9599b5be8c37266f7ded9cd2becf60",
            characterName: "레이튼",
            level: 47,
            killCount: 2,
            deathCount: 3,
            assistCount: 3,
            attackPoint: 16575,
            damagePoint: 14399,
            battlePoint: 84,
            sightPoint: 148,
            towerAttackPoint: 10051,
            backAttackCount: 8,
            comboCount: 30,
            spellCount: 1,
            healAmount: 0,
            sentinelKillCount: 39,
            demolisherKillCount: 27,
            trooperKillCount: 1,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 14490,
            spendCoin: 14050,
            spendConsumablesCoin: 2100,
            playTime: 888,
            responseTime: 60,
            minLifeTime: 111,
            maxLifeTime: 451,
          },
          position: {
            name: "근거리딜러",
            explain: "치명타 피해량 +12%",
            attribute: [
              {
                level: 1,
                id: "9892da3b4b8212f7c6d5ba94de5ed4e0",
                name: "추격자의 발걸음",
              },
              {
                level: 2,
                id: "ff6a4b6ab1d0fe84d63cace2e0c24a69",
                name: "사냥꾼의 본능",
              },
              {
                level: 3,
                id: "d10f92492701526d64b18428ec8ce0d3",
                name: "거인 사냥꾼",
              },
            ],
          },
          items: [
            {
              itemId: "b28f2935bf427fe2293e9aa60b2c8db9",
              itemName: "E 슈퍼 다이버볼트",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "5b1fed56ee36c2fb744e91fe8ee5d678",
              itemName: "S 스루드 오엘",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "7c39372a54910c43568dc54983fa2d38",
              itemName: "E 비스트 레이지",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "276645a8d5e4ea0e972471cada243637",
              itemName: "E 어드바이져",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "90c9c3b55efc91490ce5982561de96f3",
              itemName: "E 로키진스 ",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "e7979dcfe05be122364dc793afb1b842",
              itemName: "S 메탈릭 레이지",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "8a048ac87bc14ae49868ca03726e5c1c",
              itemName: "라이트닝 카미오",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "dfeab352c086e6f7fa0a8e5930f0f6eb",
              itemName: "썬더클랩 카미오",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "b891cc3c34b6215eae91af8b9c38ac26",
              itemName: "체스터 더블버거",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "5b9a8108b0b92457abc225c565fde466",
              itemName: "리세스 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "b37373156f360fb1d0805bd0d846b0b9",
              itemName: "이펙트 이펙션",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "a5829b6da66c7bb983e58fc5cc207f30",
              itemName: "솔리드 스위퍼",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "a5c8ee5c76720f0517901a1a81d6701d",
              itemName: "버스트 맥시머",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "800ceffaf1a48931f833e49bd8b00e05",
              itemName: "E 브루트 하이드로",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "a751a62b5fb2b17fa9f10cf8eda75175",
              itemName: "전자기 카미오",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "69fd0261cdd9355b9fb92d80af4e4177",
              itemName: "버스트 크래파드",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "8abac87df02214b4130c4351b59375d6",
          nickname: "앙앙민민혁혁",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 0,
            partyId: "b762303013093c43599c55f64fdcff53",
            playTypeName: "정상",
            characterId: "8ca68ab00e6f2c33220214d720c024ee",
            characterName: "에밀리",
            level: 45,
            killCount: 7,
            deathCount: 3,
            assistCount: 5,
            attackPoint: 37456,
            damagePoint: 10352,
            battlePoint: 167,
            sightPoint: 268,
            towerAttackPoint: 30339,
            backAttackCount: 36,
            comboCount: 61,
            spellCount: 0,
            healAmount: 2166,
            sentinelKillCount: 17,
            demolisherKillCount: 29,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 14690,
            spendCoin: 14400,
            spendConsumablesCoin: 3000,
            playTime: 888,
            responseTime: 79,
            minLifeTime: 105,
            maxLifeTime: 511,
          },
          position: {
            name: "원거리딜러",
            explain: "치명타 피해량 +12%",
            attribute: [
              {
                level: 1,
                id: "e29cbec17de6ae981984c6d279400483",
                name: "완벽주의자",
              },
              {
                level: 2,
                id: "43c56f15f90192f7ead0a8eba794fbed",
                name: "전장의 학살자",
              },
              {
                level: 3,
                id: "ac75b2be060e121bbea9548d599f278e",
                name: "완전한 성장",
              },
            ],
          },
          items: [
            {
              itemId: "e41b17483cc240866811b21f83dddbf6",
              itemName: "E 유레카",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "7fb6e1cf594072a24134a58fe14b0caf",
              itemName: "E 순수한 정신",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "d303204538ffcec0803a05a4c4ef7f8b",
              itemName: "S 원소의 순환",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "f67717276620d90c0dc1e3620201c310",
              itemName: "S 크리소포에이아",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "73b3ca3f327ffff1f05c357d84da4bad",
              itemName: "S 신성한 초월",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "c2d0fdeff515810a3cb590c416e7ec40",
              itemName: "S 아타노르",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "a8551b11fa0e34605485c940a77ada1c",
              itemName: "캡슐 슈터 보틀",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "692930d1982058e3a903abd97df60b12",
              itemName: "파운틴 백팩",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "88460b35b85e6bb479ba21087079150e",
              itemName: "알케미 스파클링 ",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c0432d98a1e2d21bda6e726ef4dafce3",
              itemName: "런업 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "4a01c12c5c771e2655eb26317ae7dcee",
              itemName: "파이크 이펙션",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "a5829b6da66c7bb983e58fc5cc207f30",
              itemName: "솔리드 스위퍼",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "852addcbcb8f257b352fa5a906fe8441",
              itemName: "알케믹 맥시머",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "ce4a0fda5c825776cc893e8d72b6e1a2",
              itemName: "E 아쿠아 레기아",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "e20b9ef6fddabadcf547786067b74b5e",
              itemName: "구르기 배낭",
              slotCode: "201",
              slotName: "장신구ALL",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "67e7357bbb413e79180803525cb3cbe4",
              itemName: "에메랄드 타블릿",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "1163dfae07e7cfbef54534090b3d5fdf",
          nickname: "꿀꿀별",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 2,
            partyId: "ce31afb4198335842df5f7c43beb3b6b",
            playTypeName: "정상",
            characterId: "052b8ab48199f154cbafc20a8ea7ebcf",
            characterName: "릭",
            level: 27,
            killCount: 1,
            deathCount: 3,
            assistCount: 9,
            attackPoint: 16975,
            damagePoint: 21927,
            battlePoint: 256,
            sightPoint: 321,
            towerAttackPoint: 2910,
            backAttackCount: 41,
            comboCount: 33,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 11,
            demolisherKillCount: 7,
            trooperKillCount: 2,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 10010,
            spendCoin: 8745,
            spendConsumablesCoin: 2620,
            playTime: 888,
            responseTime: 93,
            minLifeTime: 22,
            maxLifeTime: 374,
          },
          position: {
            name: "서포터",
            explain: "주변 아군의 스킬 공격력 +3%, 방어력 +4%, 회피 +4%",
            attribute: [
              {
                level: 1,
                id: "100b40cb5e22f5613492234dcba705c6",
                name: "활성화 지원",
              },
              {
                level: 2,
                id: "2ee2eeb641442593cc234332b0809202",
                name: "할인 판매",
              },
              {
                level: 3,
                id: "50ce90f1013b152718b1dcc4c3023f36",
                name: "부서진 갑옷",
              },
            ],
          },
          items: [
            {
              itemId: "0cb989b9dffc6515efe1ded9a162f9f2",
              itemName: "E 익스트림 웨이",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "d05b5b806e1e9614ad4b5a44e9b80132",
              itemName: "라잇 수브니어",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "eaa43838580f15835beb3d7ea1a6ea90",
              itemName: "E 투어리스터",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "e6c4a8829341cfb35575f833ae17dcda",
              itemName: "S 퍼페츄얼 타임",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "58c05cf33a6d03ca28d1a0b675ac10e5",
              itemName: "E 패스파인더",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "eaec37c42cb0688770d8fdfee685fda6",
              itemName: "E 롱기스트 저니",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "0df7b3d166060d358317662f2af305dd",
              itemName: "링크 베이글",
              slotCode: "201",
              slotName: "장신구ALL",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "f7db833c1c445512d8d40a6e2baf020c",
              itemName: "데스 액세서리",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "6a929b3cc53cf58b0ed2217dcb763789",
              itemName: "타키온 스파클링",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c0432d98a1e2d21bda6e726ef4dafce3",
              itemName: "런업 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "f60824ebbe51ac0bb330bc9e325b2735",
              itemName: "타키온 파이크",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "a5829b6da66c7bb983e58fc5cc207f30",
              itemName: "솔리드 스위퍼",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "a6abfd4505fb46cde75dc5b4414b60b8",
              itemName: "PS 레이더 R4",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "e612e180e8b01531b610d24f8288341c",
              itemName: "S 연결된 시간",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "529aaea05d4d8041448bbfc97673f23f",
              itemName: "SB코스믹 데브",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "c6486d0efe78d18c80603559ff290e15",
              itemName: "유니버스 레그람",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "0ae4f1beb3575fa751c583d4b8f6e05d",
          nickname: "달져",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 0,
            partyId: "b762303013093c43599c55f64fdcff53",
            playTypeName: "정상",
            characterId: "bad9955f85d80c68a40673504e67a678",
            characterName: "에바",
            level: 31,
            killCount: 1,
            deathCount: 4,
            assistCount: 10,
            attackPoint: 14569,
            damagePoint: 31879,
            battlePoint: 252,
            sightPoint: 342,
            towerAttackPoint: 1362,
            backAttackCount: 17,
            comboCount: 22,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 4,
            demolisherKillCount: 1,
            trooperKillCount: 0,
            guardianKillCount: 0,
            guardTowerKillCount: 0,
            getCoin: 10390,
            spendCoin: 9300,
            spendConsumablesCoin: 2200,
            playTime: 888,
            responseTime: 67,
            minLifeTime: 74,
            maxLifeTime: 349,
          },
          position: {
            name: "탱커",
            explain: "체력 +7%, 회피 +5%",
            attribute: [
              {
                level: 1,
                id: "a681dbe9ad002a1ebe7f9c9229de9c7d",
                name: "전선 유지",
              },
              {
                level: 2,
                id: "745942f7f2c5030a057d3c9cc3a0ce04",
                name: "수플렉스",
              },
              {
                level: 3,
                id: "6d8fb905d69edf1c9f73495c3ee44d28",
                name: "선봉장",
              },
            ],
          },
          items: [
            {
              itemId: "b2fa321c03ccf9034f185aec3e8cfe4c",
              itemName: "구원의 이기",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "8c3f5895b85665ad31b17dd4e9248bf6",
              itemName: "치퍼 에티튜드",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "f6da5ea5555ddb45eca9e53d2c6eea12",
              itemName: "DB파이터 헤르츠",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "b6ba58d9ecd2767cf63bbbd7c10c22be",
              itemName: "E 끊임없는 도전",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "fbb46798068a3cc95e04254baae70e60",
              itemName: "S 그래플링 테크닉",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "2c4fab654f831a64724d58361e3e41be",
              itemName: "E 나의 공격리듬은!",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "dcdee96c078863a3006835b11b37f9e5",
              itemName: "브레이킹 레그람",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "f2a3583c127bf79abb33655132f7c1a3",
              itemName: "스파이어 마석",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "1d8f428c1747f4fab7793fc19e59aaf5",
              itemName: "첼시 콜라 V",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "c0432d98a1e2d21bda6e726ef4dafce3",
              itemName: "런업 스프린터",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "9844098656883e4d412163f9a9f740d5",
              itemName: "파이터 파이크 ",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "74b95e7cc481ac9860b6c9b28d71db2a",
              itemName: "파이터 플래쉬 ",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "8be7e6254b58ecbf2a13e81931a7435f",
              itemName: "인사이트 엔진T7 ",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "d5ac61f4f52f10e9dd1aa4a3eacf17e6",
              itemName: "S 무도가의 자세",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "a8b60aca930b0e5b0b498b7dd9960ba1",
              itemName: "슈타이너 레그람",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "b51057b818a2b535e74bda34489000b3",
              itemName: "반잡 눈",
              slotCode: "201",
              slotName: "장신구ALL",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
        {
          playerId: "9fbaacf5e93cf721fb31c01f305847db",
          nickname: "아마도내년에는",
          map: {
            mapId: "101",
            name: "리버포드",
          },
          playInfo: {
            random: false,
            partyUserCount: 0,
            partyId: "b762303013093c43599c55f64fdcff53",
            playTypeName: "정상",
            characterId: "cf6008394ebfb5d0de83fa05834018db",
            characterName: "다이무스",
            level: 54,
            killCount: 9,
            deathCount: 2,
            assistCount: 13,
            attackPoint: 57023,
            damagePoint: 9640,
            battlePoint: 165,
            sightPoint: 257,
            towerAttackPoint: 40883,
            backAttackCount: 39,
            comboCount: 71,
            spellCount: 0,
            healAmount: 0,
            sentinelKillCount: 40,
            demolisherKillCount: 23,
            trooperKillCount: 1,
            guardianKillCount: 1,
            guardTowerKillCount: 0,
            getCoin: 17370,
            spendCoin: 16325,
            spendConsumablesCoin: 2600,
            playTime: 888,
            responseTime: 53,
            minLifeTime: 121,
            maxLifeTime: 379,
          },
          position: {
            name: "근거리딜러",
            explain: "치명타 피해량 +12%",
            attribute: [
              {
                level: 1,
                id: "d10f92492701526d64b18428ec8ce0d3",
                name: "거인 사냥꾼",
              },
              {
                level: 2,
                id: "43c56f15f90192f7ead0a8eba794fbed",
                name: "전장의 학살자",
              },
              {
                level: 3,
                id: "47b288f44ffb19009e9d2adc73c62472",
                name: "최후의 일격",
              },
            ],
          },
          items: [
            {
              itemId: "c214ffc50f3ee8b991d81c71520449c5",
              itemName: "E 메이헨 슈나이더",
              slotCode: "101",
              slotName: "손(공격)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "101",
              equipSlotName: "손(공격)",
            },
            {
              itemId: "538760d675a4ca500033d2c406627bf0",
              itemName: "S 베스페리아 ",
              slotCode: "102",
              slotName: "머리(치명)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "102",
              equipSlotName: "머리(치명)",
            },
            {
              itemId: "c116b0c96cc797a35dbe1c6e900f314d",
              itemName: "E 우아한 궤적",
              slotCode: "103",
              slotName: "가슴(체력)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "103",
              equipSlotName: "가슴(체력)",
            },
            {
              itemId: "9456760ffcf766a8eaf14920f811916e",
              itemName: "S 골드 샤르페",
              slotCode: "104",
              slotName: "허리(회피)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "104",
              equipSlotName: "허리(회피)",
            },
            {
              itemId: "0386090dfb842186519a733ade7686f6",
              itemName: "S 펄션 필러 ",
              slotCode: "105",
              slotName: "다리(방어)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "105",
              equipSlotName: "다리(방어)",
            },
            {
              itemId: "2339de62a08da5e7f6e9d611191131e5",
              itemName: "E 슈발츠 슈트름",
              slotCode: "106",
              slotName: "발(이동)",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "106",
              equipSlotName: "발(이동)",
            },
            {
              itemId: "e61b559ae6620fa162637d3a70da2ed5",
              itemName: "장작 베리드",
              slotCode: "202",
              slotName: "장신구1",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "202",
              equipSlotName: "장신구1",
            },
            {
              itemId: "014e21eb551c896a9b8c39a7d9019f64",
              itemName: "SB질풍의 루차",
              slotCode: "203",
              slotName: "장신구2",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "203",
              equipSlotName: "장신구2",
            },
            {
              itemId: "279ed8abac5f935122888de0c4a42044",
              itemName: "액트 스파클링 ",
              slotCode: "301",
              slotName: "회복킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "301",
              equipSlotName: "회복킷",
            },
            {
              itemId: "e4c35f1ee24d6d4bd940b22b5a262644",
              itemName: "질풍의 엑셀",
              slotCode: "302",
              slotName: "가속킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "302",
              equipSlotName: "가속킷",
            },
            {
              itemId: "64f1758bbc6d836cdec206c2a2876e7f",
              itemName: "질풍의 이펙트 ",
              slotCode: "303",
              slotName: "공격킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "303",
              equipSlotName: "공격킷",
            },
            {
              itemId: "a5829b6da66c7bb983e58fc5cc207f30",
              itemName: "솔리드 스위퍼",
              slotCode: "304",
              slotName: "방어킷",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "304",
              equipSlotName: "방어킷",
            },
            {
              itemId: "54430bd9be1d8cc0948891f3a159c92d",
              itemName: "보름달 임팩트",
              slotCode: "305",
              slotName: "특수킷",
              rarityCode: "102",
              rarityName: "언커먼",
              equipSlotCode: "305",
              equipSlotName: "특수킷",
            },
            {
              itemId: "9beaa3114939ca52fba36c5203b15d64",
              itemName: "E 솔리튜드 칼리버",
              slotCode: "107",
              slotName: "목",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "107",
              equipSlotName: "목",
            },
            {
              itemId: "398c3e312e899190658422f4bda4666a",
              itemName: "보름달 베리드",
              slotCode: "204",
              slotName: "장신구3",
              rarityCode: "103",
              rarityName: "레어",
              equipSlotCode: "204",
              equipSlotName: "장신구3",
            },
            {
              itemId: "e04cba10478b3d94a9fa77f724b85182",
              itemName: "쉬베르트 루프리",
              slotCode: "205",
              slotName: "장신구4",
              rarityCode: "104",
              rarityName: "유니크",
              equipSlotCode: "205",
              equipSlotName: "장신구4",
            },
          ],
        },
      ],
    },
  });
}

export default useMatchDetailQuery;
